### ISSUE TITLE
Events schema & events content

### ISSUE THREAD

**Issue by jojokarlin** [nyu-dh/nyu-dh.github.io#27]
Show what has happened
- Open houses
- NYCDH Week Seed Grant workshop
- NYCDH Week Data Viz workshop
- Public Humanities workshops

**Comment by coblezc** [comment]
https://github.com/nyu-dh/nyu-dh.github.io/commit/8d8bc3f4625a849316ad850f79de9ae9da1e7ba8

I copied the news item template and added the following fields:

eventDate: distinct from the [publication] date field
startTime: when the event starts
endTime: when the event ends
location: location of the event
link: ideally a link to the registration page; zoom link could suffice.


Questions:

- will events appear alongside news on https://nyu-dh.github.io/news/, or have a separate page?
- similarly, store events md files in _news, or somewhere else?
- news items cards currently display the publication date. event item cards should presumably instead display the eventDate. will this be confusing for users?
