### ISSUE TITLE
Finalize content for Courses page

### ISSUE THREAD

**Issue by mnyrop** [nyu-dh/nyu-dh.github.io#38]
See: https://nyu-dh.github.io/curriculum/courses/

**Comment by coblezc** [comment]
- I propose that this page list courses for two semesters: the current one and the upcoming one.
- Should we document past course descriptions somewhere (and does that need to be public/online)? Some depts do (https://as.nyu.edu/english/graduate/past-courses-.html), some don't.
- @bmschmidt Can you confirm or update the description and link for Intro to Programming. Also, confirm that it will be offered Fall 2022. Also, do both of your certificate courses have 1121 as the course code?

**Comment by coblezc** [comment]
done (overlaps with https://github.com/nyu-dh/nyu-dh.github.io/issues/47)
