### ISSUE TITLE
(Re)design project cards

### ISSUE THREAD

**Issue by mnyrop** [nyu-dh/nyu-dh.github.io#43]
Contingent on #12 

- [x] add project thumb img alt-titles
- [x] @bmschmidt to add preliminary `tags` and `featured` values to spreadsheet (copied over from: https://github.com/nyu-dh/nyu-dh.github.io/issues/60)
- [x] @mnyrop to implement `featured` grouping on `/project` root page

**Comment by coblezc** [comment]
[ ] add project thumb img alt-titles?
