### ISSUE TITLE
Don't link to category pages on mobile

### ISSUE THREAD

**Issue by bmschmidt** [nyu-dh/nyu-dh.github.io#78]
<img width="201" alt="image" src="https://user-images.githubusercontent.com/1110758/167178749-059f1309-bb42-4470-8aad-3eff71cce701.png">

"curriculum" looks clickable here on a mobile screen size, but nothing happens.

**Comment by mnyrop** [comment]
Moved to https://github.com/nyu-dh/nyu-dh.github.io/issues/53
